export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_DETAIL_COUNTRY = "GET_DETAIL_COUNTRY";
export const GET_COUNTRY_BY_NAME = "GET_COUNTRY_BY_NAME"; 
export const GET_CONTINENT_LIST = "GET_CONTINENT_LIST";
export const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT";
export const ORDER="ORDER"
export const GET_ACTIVITIES="GET_ACTIVITIES"
export const POST_NEW_ACTIVITY="POST_NEW_ACTIVITY"
export const EDIT_ACTIVITY="EDIT_ACTIVITY"


