//ACTIVITIES:
export const EDIT_ACTIVITY = "EDIT_ACTIVITY";
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";
export const POST_NEW_ACTIVITY = "POST_NEW_ACTIVITY";
//COUNTRIES:
export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_DETAIL_COUNTRY = "GET_DETAIL_COUNTRY";
export const GET_COUNTRY_BY_NAME = "GET_COUNTRY_BY_NAME";
//CONTINENT
export const GET_CONTINENT_LIST = "GET_CONTINENT_LIST";
//FILTERS
export const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT";
//ORDERS 
export const ORDER = "ORDER";
